# Generated by Django 5.2 on 2025-05-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_productimages_productimage'),
        ('users', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
    ]
