# Generated by Django 5.2 on 2025-07-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ciudad',
            field=models.CharField(default='sin ciudad', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='departamento',
            field=models.CharField(default='sin departamento', max_length=100),
        ),
    ]
