# Generated by Django 5.2 on 2025-07-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_order_ciudad_order_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='was_paid',
            field=models.BooleanField(default=False),
        ),
    ]
