# Generated by Django 5.2 on 2025-07-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_order_was_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='was_paid',
        ),
    ]
